---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "ampcombi_ampcombi"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::ampcombi=0.1.7
  - pandas=1.0.5
