---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "ampcombi_parsetables"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::ampcombi=0.2.1"
